name: epimetheus-http4s
baseurl: /epimetheus-http4s
description: Epimetheus Http4s Metrics
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
