name: epimetheus-http4s
baseurl: /epimetheus-http4s
description: Epimetheus Http4s Metrics
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-RC1+41-33b82536-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
